### ISSUE TITLE
公式编号格式无法显示

### ISSUE THREAD

**Issue by zihao-zheng** [lihanshu/NWPU-Thesis-Template#2]
在cls格式文件中公式定义的连字符为"-"，但编译后显示"."
<img width="738" alt="image" src="https://github.com/lihanshu/NWPU-Thesis-Template/assets/62669030/9356432b-74d3-48ec-b56f-e15d1e4a0559">
<img width="450" alt="image" src="https://github.com/lihanshu/NWPU-Thesis-Template/assets/62669030/54a88a62-79f2-40e9-b910-2dc10166c6f5">

**Comment by lihanshu** [comment]
在 https://github.com/lihanshu/NWPU-Thesis-Template/commit/1ad7cb8805d507c4bf2d9d6d430154d98c9a122c 中已解决。
